//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p03_SilverProducts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Items { get; set; }
        public string Period { get; set; }
        public Nullable<double> Price { get; set; }
        public string Image { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public string Status { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Depth { get; set; }
        public Nullable<double> Weight { get; set; }
        public string History { get; set; }
    }
}
